### ISSUE TITLE
php composer - trace

### ISSUE THREAD

**Issue by ze42** [jvoisin/snuffleupagus#307]
Hello,

Simulation mode only. After some time, I get a trace, with a `PHP Fatal` on some snuffleupagus... thought I'm only in simulation.

Snuffleupagus rules:
```
sp.disable_function.function("function_exists").simulation().drop();
```

Running composer:
```
$ php ./composer.phar 
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/composer/autoload_real.php on line 26
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/polyfill-ctype/bootstrap.php on line 14
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/polyfill-mbstring/bootstrap.php on line 14
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/polyfill-mbstring/bootstrap.php on line 54
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/bin/composer on line 25
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/src/Composer/Console/Application.php on line 69

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/src/Composer/Console/Application.php on line 69
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/src/Composer/Console/Application.php on line 74

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/src/Composer/Console/Application.php on line 74
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/src/Composer/Console/Application.php on line 74

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/src/Composer/Console/Application.php on line 74
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/ConsoleOutput.php on line 124

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/ConsoleOutput.php on line 124
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/StreamOutput.php on line 112

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/StreamOutput.php on line 112
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/ConsoleOutput.php on line 124

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/ConsoleOutput.php on line 124
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/StreamOutput.php on line 112

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Output/StreamOutput.php on line 112
PHP Warning:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php on line 797

Warning: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php on line 797

PHP Fatal error:  Uncaught ErrorException: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php:947
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, '[snuffleupagus]...', 'phar:///home/ze...', 947, Array)
#1 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(947): function_exists('proc_open')
#2 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(753): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(714): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderEx in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php on line 947

Fatal error: Uncaught ErrorException: [snuffleupagus][disabled_function] Aborted execution on call of the function 'function_exists' in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php:947
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, '[snuffleupagus]...', 'phar:///home/ze...', 947, Array)
#1 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(947): function_exists('proc_open')
#2 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(753): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(714): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php(127): Symfony\Component\Console\Application->renderEx in phar:///home/ze/composer/composer.phar/vendor/symfony/console/Application.php on line 947
```

Note, used the following doc to get composer to start with:
https://getcomposer.org/download/

a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1  composer-setup.php
7ff2e82bd39b479172df744abbc0c39a047a6e61277ab0bc12fb885c939bff60b520082b5647e63e0fa065332d742b33  composer.phar

Running php 7.2, tested with `0.5.0` and `master`.

Edit: Tested with latest versions.

**Comment by jvoisin** [comment]
This is weird.
I'll try to investigate this month (since I'm currently moving into a new place, I don't have a lot of free time right now).

**Comment by buixor** [comment]
Investigated a bit, and the function `getSttyColumns` (in Application.php:947) does a `function_exists('proc_open')` call.

The error itself is generated by `ErrorHandler::handle` (in Util/ErrorHandler.php:38) _probably_ because of the following :

```php
if ($level !== E_DEPRECATED && $level !== E_USER_DEPRECATED) {
throw new \ErrorException($message, 0, $level, $file, $line);
}

```

My guess is that it catches php's error logs and the $level generated by SP is not one of the expected ones, leading to the Exception we see in the debug log.

**Comment by ze42** [comment]
Looking at https://github.com/nbs-system/snuffleupagus/pull/308/files#diff-0d53bfd53e88b5426e0fff207297e92fR22 I would say it always log to errors...

```
-      int syslog_level = SP_LOG_DROP ? LOG_ERR : LOG_INFO;
+      int syslog_level = type == SP_LOG_DROP ? LOG_ERR : LOG_INFO;
```

Or better yet, have a function to translate all `SP_LOG_...` into syslog loglevels.

**Comment by jvoisin** [comment]
Done I think
