### ISSUE TITLE
UBSan reports

### ISSUE THREAD

**Issue by cgzones** [jvoisin/snuffleupagus#491]
While running the testsuite under UBSan several tests fail:

`make CC='gcc-14 -O1 -g -fno-omit-frame-pointer -fsanitize=undefined' tests`

```
FAILED TEST SUMMARY
---------------------------------------------------------------------
Non-existent configuration file in a list [tests/inexistent_conf_file_list.phpt]
phpinfo() showing snuffleupagus [tests/phpinfo_presence.phpt]
Check the phplog output with a log_max_len [tests/phplog_max_len.phpt]
Shipped configuration (rips) [tests/rips_configuration.phpt]
Shipped configuration [tests/shipped_configuration.phpt]
```

The failures originate from two reasons:

```
src/sp_config_scanner.c:388:15: runtime error: index -30 out of bounds for type 'unsigned char [256]'
    #0 0x70895576990c in sp_config_scan src/sp_config_scanner.c:388
    #1 0x708955722cd3 in sp_parse_config src/sp_config.c:62
    #2 0x70895571e6cf in OnUpdateConfiguration src/snuffleupagus.c:522
    #3 0x6010be1af646 in zend_register_ini_entries_ex (/usr/bin/php8.2+0x36d646) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #4 0x70895571cae1 in zm_startup_snuffleupagus src/snuffleupagus.c:121
    #5 0x6010be13f0df in zend_startup_module_ex (/usr/bin/php8.2+0x2fd0df) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #6 0x6010be13f17f  (/usr/bin/php8.2+0x2fd17f) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #7 0x6010be14d66a in zend_hash_apply (/usr/bin/php8.2+0x30b66a) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #8 0x6010be0d40b5 in php_module_startup (/usr/bin/php8.2+0x2920b5) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #9 0x6010bdf6a265  (/usr/bin/php8.2+0x128265) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #10 0x70895792ec89 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #11 0x70895792ed44 in __libc_start_main_impl ../csu/libc-start.c:360
    #12 0x6010bdf6b550 in _start (/usr/bin/php8.2+0x129550) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/sp_config_scanner.c:388:15 in
```
```
src/sp_config.c:207:20: runtime error: store to misaligned address 0x796d1f9a78d4 for type 'u_long', which requires 8 byte alignment
0x796d1f9a78d4: note: pointer points here
  00 00 00 00 ff 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00
              ^
    #0 0x796d1f92251a in parse_ulong src/sp_config.c:207
    #1 0x796d1f9239a9 in sp_process_rule src/sp_config.c:76
    #2 0x796d1f92404f in sp_process_config_root src/sp_config.c:31
    #3 0x796d1f96770d in sp_config_scan src/sp_config_scanner.c:1482
    #4 0x796d1f922cd3 in sp_parse_config src/sp_config.c:62
    #5 0x796d1f91e6cf in OnUpdateConfiguration src/snuffleupagus.c:522
    #6 0x598aae727646 in zend_register_ini_entries_ex (/usr/bin/php8.2+0x36d646) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #7 0x796d1f91cae1 in zm_startup_snuffleupagus src/snuffleupagus.c:121
    #8 0x598aae6b70df in zend_startup_module_ex (/usr/bin/php8.2+0x2fd0df) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #9 0x598aae6b717f  (/usr/bin/php8.2+0x2fd17f) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #10 0x598aae6c566a in zend_hash_apply (/usr/bin/php8.2+0x30b66a) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #11 0x598aae64c0b5 in php_module_startup (/usr/bin/php8.2+0x2920b5) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #12 0x598aae4e2265  (/usr/bin/php8.2+0x128265) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)
    #13 0x796d21b4dc89 in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #14 0x796d21b4dd44 in __libc_start_main_impl ../csu/libc-start.c:360
    #15 0x598aae4e3550 in _start (/usr/bin/php8.2+0x129550) (BuildId: 5228f916ded87172ddf0f3eca448f1e43874d60f)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior src/sp_config.c:207:20 in
```

**Comment by jvoisin** [comment]
Fixed by 358bd3d and 4a486d7, thanks!
